### ISSUE TITLE
Better macosx support

### ISSUE THREAD

**Issue by dbuenzli** [ocamlsdl/OCamlSDL#5]
It seems that the call to `ocamlmklib` does not include the needed `-framework Cocoa` (at least in the version distributed by opam). Which leads to complication for end users. It would be nice to fix this. See:

http://stackoverflow.com/questions/30239496/using-ocamlbuild-to-build-sdl-and-opengl-application

**Comment by nilsbecker** [comment]
wow, finally i found this after trying to compile sdlgears for a while. the SO answer works. maybe as a temporary fix it would be good to update README.macosx.  the include directories should be `-I +../sdl` not `-I +sdl` and one can add manually `-cclib "-framework Cocoa"` in the linking step.
